# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_run_OT <- function(XX, YY, COST_XY, EPS, LAMBDA1, LAMBDA2, balance, highLAM_lowMU, conv, max_iter, show, show_iter) {
    .Call('_ROKET_Rcpp_run_OT', PACKAGE = 'ROKET', XX, YY, COST_XY, EPS, LAMBDA1, LAMBDA2, balance, highLAM_lowMU, conv, max_iter, show, show_iter)
}

Rcpp_run_full_OT <- function(COST, ZZ, EPS, LAMBDA1, LAMBDA2, balance = FALSE, highLAM_lowMU = TRUE, conv = 1e-5, max_iter = 3e3L, ncores = 1L, show = TRUE, show_iter = 50L) {
    .Call('_ROKET_Rcpp_run_full_OT', PACKAGE = 'ROKET', COST, ZZ, EPS, LAMBDA1, LAMBDA2, balance, highLAM_lowMU, conv, max_iter, ncores, show, show_iter)
}

Rcpp_KernTest <- function(RESI, KK, nPERMS = 2e3L, iter1 = 50L, iter2 = 1e3L, verbose = FALSE) {
    .Call('_ROKET_Rcpp_KernTest', PACKAGE = 'ROKET', RESI, KK, nPERMS, iter1, iter2, verbose)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_ROKET_RcppExport_registerCCallable', PACKAGE = 'ROKET')
})
